[package]
name = "sqruff-md"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
fern = "0.7.1"
glob = "0.3.2"
log = "0.4.28"
markdown = "1.0.0"
sqruff-lib = "0.28.2"
