on:
  pull_request:
  merge_group:

name: Build
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-binaries:
    name: Build binaries for all platformsasd1231
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: sqruff-md-linux-x86_64-musl
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            bin: sqruff-md

          - name: sqruff-md-linux-aarch64-musl
            os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            bin: sqruff-md

          - name: sqruff-md-windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: sqruff-md.exe

          - name: sqruff-darwin-x86_64
            os: macos-13
            target: x86_64-apple-darwin
            bin: sqruff-md

          - name: sqruff-md-darwin-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: sqruff-md
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@1db091d29dbc56b9ae809cdee70bd948737918f7 # ratchet:houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          toolchain: stable
          args: --locked --release
          strip: true
      - name: Upload
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # ratchet:actions/upload-artifact@v4
        with:
          name: sqruff-md-${{ matrix.platform.name}}
          path: target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
